- name: Install nginx
  apt:
    name: nginx
    state: present
  when: ansible_facts ['os_family'] == 'Debian'

- name: Generate Nginx site config
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/site.conf
    owner: root
    group: root
    mode: 0744

#Generate the site Index file
- name: Generate index.html
  template:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0744
    
#Enabling the nginx as System d
- name: Enable Nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started